version: "2.18"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    volumes:
      - ./data01:/usr/share/elasticsearch/data
    environment:
      node.name: "es01"
      cluster.name: es-docker-cluster
      cluster.initial_master_nodes: "es01"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      elasticsearch_network:
        aliases:
          - elasticsearch_host
volumes:
  data01:
    driver: local
networks:
  elasticsearch_network:
